### ISSUE TITLE
Brw - rad - Diffuse BW: unrealistic data (since at least 2018-07-28)

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#1]
Starting in 2018-07-28 the Diffuse BW channel is increasingly showing unrealistically large values that exceed the DW shortwave.

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/brw/2018/gradobs.brw-rad.20180728.quicklook.jpg)

**Comment by gmd-jw** [comment]
Confirmed that moving the signal to a different channel on the mux resolved the problem.
