### ISSUE TITLE
brw - soil - snow depth: all year long at ~3600

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#10]
The snow depth is always at ~3600mm no matter if its January or July. I doubt that is real?!? The top soil temp is positive after all!

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/brw/2018/gradobs.brw-soil.20180701.quicklook.jpg)

**Comment by gmd-jw** [comment]
This number isn't really snow depth, but distance (in mm) from the sensor to the ground. The data should be averaged during the summer to determine sensor height, and then used to determine snow depth in the winter.
