### ISSUE TITLE
brw - soil_temp: coinciding oszillation in different temp channels

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#11]
Barrows soil temperature sensor shows oszillations. Is that new or a known thing?

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/brw/2018/gradobs.brw-soil.20181005.quicklook.jpg)

**Comment by gmd-jw** [comment]
oscillations near the surface could be real, but too hard to tell with the current plots.

**Comment by gmd-jw** [comment]
After taking a closer look at the raw data, the oscillations do not look real. They also appear at depth, which isn't likely. I have changed the technique used to measure the thermistors, including the PIR, to see if there is an improvement. I did not see any oscillations before or after the program change when monitoring the data in real-time (for about 1 hr.).

**Comment by hagne** [comment]
I will keep an eye open if the oscillations persist.

**Comment by gmd-jw** [comment]
Confirmed by looking at data in real-time that we are just noticing the resolution of the datalogger.
