### ISSUE TITLE
BRW: sp02 spikes

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#13]
many of the channels show spikes and in addition the direct 610nm channel has extended dropout periods

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/brw/2018/gradobs.brw-sp02.20181020.quicklook.jpg)

**Comment by Crepinsek** [comment]
Likely an issue with cables since the issue started after on-site tech made new cables. Jim will make new cables to go out.

**Comment by Crepinsek** [comment]
Instruments also needs to be readjusted after calibration at MLO since the top of the measurement is getting chopped off

**Comment by gmd-jw** [comment]
new cables made for SP02s when they pulled for cals at MLO.
