### ISSUE TITLE
mlo - rad - direct normal3 looks dead

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#14]
rad direct normal 3 is almost completely flat. Also how can it be that "diffuse BW" is higher then "DW shortwave"?

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/mlo/2018/gradobs.mlo-rad.20181021.quicklook.jpg)

**Comment by gmd-jw** [comment]
The Eppley trackers use a Garmin GPS, which just started reporting the 
year as 2099 on 10/22. The solar calculations in the controller are 
therefor not working. MLO has 2 trackers, one is a Kipp & Zonen 2AP and 
the other is an Eppley. SMO only has an Eppley, so the diffuse will be 
off too.

Garmin is working on a fix.

Jim

**Comment by gmd-jw** [comment]
Interim fix sent to MLO.
