### ISSUE TITLE
brw - alb - We lost it!

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#16]
Looks like we are not getting anything real from the albedo rack since a few days now ... sorry I wasn't checking the last few days. With no data I mean that all data is invalid (-7999).

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/brw/2018/gradobs.brw-alb.20181022.quicklook.jpg)

**Comment by gmd-jw** [comment]
The ultrasonic snow depth sensor failed, causing logger input to exceed max common mode voltage, which caused out-of-range data readings. Ultrasonic sensor unplugged until we locate the problem.
