### ISSUE TITLE
brw - soil - No data for a few days

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#17]
This stopped working in the same moment as the albedo in [issue 16](https://github.com/hagne/data_baseline/issues/16). I am actually not sure where this data is stored. There is no "soil" file. 

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/brw/2018/gradobs.brw-soil.20181022.quicklook.jpg)

**Comment by gmd-jw** [comment]
Same issue as other channels, due to failed snow depth sensor.
