### ISSUE TITLE
mlo - rad - direct normal 2 is doing strange things

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#18]
Not sure if this is related to [issue #14](https://github.com/hagne/data_baseline/issues/14). direct normal 2 (yellow line) looks strange. I can't really tell if there was any direct normal 2 before. When I look in the raw, I can't really tell what data would be ascociated with this channel. Do we have the header information somewhere (I could not find it in my stuff). Maybe we could store the header files here on Github too?!?

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/mlo/2018/gradobs.mlo-rad.20181024.quicklook.jpg)

**Comment by Crepinsek** [comment]
Duplicate instruments are no longer being plotted, so DirectNormal2 and 3 are no longer an issue.
