### ISSUE TITLE
sum - rad - dw_shortwave no data

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#19]
There seams to be no data from the dw short wave channel ... only a blip here and there.

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/sum/2018/gradobs.sum-rad.20181019.quicklook.jpg)

**Comment by gmd-jw** [comment]
Nothing I can do here. This is Koni's system.

**Comment by Crepinsek** [comment]
This is Koni's system so we cannot troubleshoot.
