### ISSUE TITLE
Brw - rad - DW Longwave: occasional spikes (started a long time ago)

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#2]
Starting at least 2018-07-28 the DW Longwave channel shows spikes that from my understanding at not physically possible?!?

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/brw/2018/gradobs.brw-rad.20180728.quicklook.jpg)

**Comment by hagne** [comment]
The DW Longwave now has not only spikes but gaps. When ever there is straight line like at 20h there is gap.


![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/brw/2018/gradobs.brw-rad.20181009.quicklook.jpg)

**Comment by gmd-jw** [comment]
Confirmed that moving the signal to a different channel on the mux resolved the problem.
