### ISSUE TITLE
brw - rad - DW Longwave and dome temp spiky

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#22]
spiky data ... see for your self
![](https://raw.githubusercontent.com/hagne/data_baseline/master/issue_figures/brw_rad_spiky.png)

**Comment by hagne** [comment]
The longwave and the dome temp is better, but now the sortwave is spiky ... is this related or does it deserve a separate ticket?

![](https://raw.githubusercontent.com/hagne/data_baseline/master/issue_figures/brw_rad_downwellingShort_spiky.png)

**Comment by Crepinsek** [comment]
These are likely issues with the connectors. Jim will work on sending new connectors down.
