### ISSUE TITLE
kwj - met - all flat-lined

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#24]
All met channels experinced a sudden offset and then flat-lined on 11/21/18. 
This probably related to the email which was just sent out by Chris:
"""
All,

This does appear to be a real problem with the fan at Kwajalein. It has been zero (not spinning) for at least the last 3 days. Can someone please contact the site? Thanks!

Chris
"""
![](https://raw.githubusercontent.com/hagne/data_baseline/master/issue_figures/kwj_met_total_fail.png)

**Comment by Crepinsek** [comment]
Fans are dead at KWJ. After discussions with Diane et al. this station will likely not be maintained. No plan to fix these instruments currently.

**Comment by hagne** [comment]
@gmd-jw 
Does this apply to all measurements? 
With other words, is there any need to look at the data at all?

**Comment by gmd-jw** [comment]
Forget Kwaj.
The site is off.
We are trying to get our equipment back.

Jim
