### ISSUE TITLE
ceilometer P0510654

### ISSUE THREAD

**Issue by gmd-jw** [hagne/data_baseline#25]
BL-View data not coming in. Checked laptop using remotePC. Found:
![capture1](https://user-images.githubusercontent.com/43865002/49168703-fc7f1700-f32f-11e8-9882-49a05d38f391.PNG)

Verified BL-View and script not running.
Restarted BL-View with script.

**Comment by cherrera1011** [comment]
Issue resolved for now. If this keeps happening I will have to contact Vaisala.
