### ISSUE TITLE
Brw - alb - all: No data since 2018-09-20

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#3]
There does not seam to be albedo data comming in since 2018-09-20.

**Comment by hagne** [comment]
Data is coming again since 2018-10-01 but UW-Longwave is missing.
will keep an eye on it for a few more days before closing

**Comment by hagne** [comment]
Some connection need to be fixed to get the UW-Longwave ... someone is working on it.

**Comment by hagne** [comment]
There is also something fishy with the dome temperature. First of all its always only one channel, but that there is some strange change in color of the graph ... did the column name change? Or did some connection get swapped out?


![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/brw/2018/gradobs.brw-alb.20181003.quicklook.jpg)

**Comment by hagne** [comment]
@gmd-jw 
Looks like we have all the channels running now. Should we close this issue? 

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/brw/2018/gradobs.brw-alb.20181008.quicklook.jpg)

**Comment by gmd-jw** [comment]
The new Barrow albedo rack acquisition should be operating properly now.
We verified PIR case and dome wiring yesterday.
