### ISSUE TITLE
brw - sp02 - tmp: temperature of sp02 #2 is dead

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#30]
First sign of a problem on 10/20 eventually died 10/22.
![](https://raw.githubusercontent.com/Crepinsek/BaselineObsLog/master/issue_figures/Screenshot_20191022_152624.png)

**Comment by hagne** [comment]
@gmd-jw Have they SP02s been taken down for the season? Does that get reported somewhere?
I am asking, since both signals are gone now.

**Comment by gmd-jw** [comment]
New cables were made when both SP02s were sent out to MLO for annual cals.
