### ISSUE TITLE
BER - where exactly is this station?!?

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#32]
Rather than using our acronyms Derek is using [GAWSIS](https://gawsis.meteoswiss.ch/GAWSIS/#/search/station/stationReportDetails/0-20008-0-BMD) acronyms. While trying to match stations we came across some irregularities ... the coordinates simply do not match.
According to the GMD webpage we are located [here](https://www.google.com/maps/place/32%C2%B018'03.6%22N+64%C2%B045'57.6%22W/@32.3019797,-64.7678781,836m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d32.301!4d-64.766)
while GAWSIS says we are [here](https://www.google.com/maps/place/32%C2%B022'12.0%22N+64%C2%B041'46.0%22W/@32.369666,-64.7011809,3283m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d32.3699989!4d-64.6961136)
Does anyone know whats wrong?
And btw, can someone please unlock [this keyhole](https://www.google.com/maps/place/Lovers+Lake/@32.3689692,-64.7165484,3093m/data=!3m1!1e3!4m13!1m7!3m6!1s0x0:0x0!2zMzLCsDIyJzEyLjAiTiA2NMKwNDEnNDYuMCJX!3b1!8m2!3d32.3699989!4d-64.6961136!3m4!1s0x8a2d6d51652c1971:0x8bf7aeb892ad7fd1!8m2!3d32.3678482!4d-64.7096323).

**Comment by gmd-jw** [comment]
The GMD web page is correct with the system location. The GAWSIS location is pointing to BIOS, our collaborator.
