### ISSUE TITLE
What to do with redundant measurments

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#34]
The way Derek's quicklook tool is written it is not straight forward to add identical data streams. For example, Mauna Loa has two direct normal measurements. The question is, do both data streams need to be monitored in quicklooks?

**Comment by Derek-Hageman-NOAA** [comment]
This might be less of a problem than even appears: for MLO and KWJ all the data in that field is missing (empty columns).  So the instrument might not even actually be there anymore.

The last reasonable MLO data looks like it ends on 2017-12-29 and KWJ on 2019-02-26.

The only "active" duplications I can find are from BLD.

However, the general question may remains: it's a bit difficult to add things to the web plots for station specific changes.  I can, however, add a trace for all stations there (e.g. just add another trace to the downwelling shortwave plot).  I think the plotting function will hide it if it's all missing, but that doesn't catch the case of configured but not sensible data (e.g. instrument simply disconnected without a CR1000 program update).

**Comment by hagne** [comment]
I guess this is ready to be archived ... we might get back to it at some point.
