### ISSUE TITLE
Brw - rad - connection failing 98% of the time

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#4]
- The connection to barrow keeps failing. 
- As a result the data comes in short. Although the data keeps up, Sara's processing does not and quicklook plots remain truncated.

**Comment by gmd-jw** [comment]
Comms restored when AP used for albedo rack was removed, but we need the AP for the albedo rack data. Working on AP configuration...

**Comment by gmd-jw** [comment]
Replacement AP (different model) sent to BRW.

**Comment by Crepinsek** [comment]
New access point for communications was installed by Bryan on-site. Jim is now able to communicate with both the albedo and tracker to troubleshoot. Data transfers are back to normal after new access point installation.
