### ISSUE TITLE
BER: Issue affecting multiple instruments and fans 2020/04/28 

### ISSUE THREAD

**Issue by emielhall** [hagne/data_baseline#45]
Issue started around 0100 UTC on 2020/04/28 and lasted until approximately 0700 UTC. Spikes/noise can be seen in all channels of the SP02 as well as the SP02 heater. Noise is also seen in the air temperature but not the relative humidity. All of the DC fans were affected during this time. The Global and Diffuse fans recovered after 0700, but the PIR fan is now dead.  The noise doesn't appear to show up in the shortwave or longwave radiation plots. 

Plots available here: https://www.esrl.noaa.gov/gmd/grad/obs/obsplot.php?sta=bmw&type=cal
Choose the raw plots to see the fan tach.

**Comment by emielhall** [comment]
The PIR fan started running again on 2020/04/30 around 1800 UTC. I emailed Dan at BIOS and it sounds like Jim gave him instructions on how to fix the fan. The dead fan's wires had the insulation fail and caused a short. Dan replaced the fan and things look to be working again. Jim plans to send some new spares down to the site.
![image](https://user-images.githubusercontent.com/47643927/80833897-d278f680-8bac-11ea-9257-ffc9ba57c82b.png)

**Comment by gmd-jw** [comment]
Dan replaced the PIR fan.
The problem that appeared to effect the 12VDC power was actually the PIR 
fan death.
Dan sent the following photo of the bad PIR fan.



emielhall wrote on 5/1/2020 12:25:

**Comment by emielhall** [comment]
I haven't seen any of these issues again after the ventilator fan was replaced. Seems like that was causing the spikes in the other data streams. I think this issue is resolved.
