### ISSUE TITLE
mlo - sp02 - all noise

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#5]
The sp02 data from mlo is all noise

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/mlo/2018/gradobs.mlo-sp02.20181002.quicklook.jpg)

**Comment by hagne** [comment]
No instrument installed!!
But shouldn't we have one installed here?!?

**Comment by gmd-jw** [comment]
Working on new heat controllers (2), and refurbishing 2 SP02's that can live at MLO.

**Comment by hagne** [comment]
Shouldn't this stay until the new/refurbished instruments are up an running? Or do you prefer this off the list for uncluttering purposes?
