### ISSUE TITLE
spo - sp02 - bad data

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#6]
![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/spo/2018/gradobs.spo-sp02.20180929.quicklook.jpg)

**Comment by hagne** [comment]
There is currently no SP02 instrument installed.
@Jim: Should we close this or need it as a reminder?

**Comment by gmd-jw** [comment]
We should leave the ticket open until the instrument is installed the summer.

**Comment by gmd-jw** [comment]
Testing new heat controller for SPO along with refurbished SP02 destined for MLO.

**Comment by gmd-jw** [comment]
SP02 & heat controller has been shipped to SPO, should arrive around Christmas -time.

**Comment by Crepinsek** [comment]
SP02 was installed on Jan.19, 2019 at 03:30 UTC.
