### ISSUE TITLE
brw - sp02 -tmp: spiky

### ISSUE THREAD

**Issue by hagne** [hagne/data_baseline#9]
I think is known for a while but it was still missing here:
Spikes in the sp02_2 temperature

![](https://www.esrl.noaa.gov/gmd/webdata/grad/obs/brw/2018/gradobs.brw-sp02.20181003.quicklook.jpg)

**Comment by gmd-jw** [comment]
New data logger program sent to Barrow by email, and programmed by Ross 10/8/2018.
New program shifts the SP02#2 T channel and the diffuse instrument to new channels on the mux, along with turning off the autorange feature.

We still have very intermittent comms with DigiOnes at Barrow, and thus unable to upload new software.

**Comment by gmd-jw** [comment]
Confirmed that moving the signal to a different channel on the mux resolved the problem.
